version: '1.0'
services:
        bot:
                build: .
                command: python main.py
                volumes:
                        - .:/code
                restart: unless-stopped
